### ISSUE TITLE
Deleting existing version bump branch fails

### ISSUE THREAD

**Issue by betatim** [henchbot/mybinder.org-upgrades#10]
I tried to persuade henchbot to be happy again but somehow failed :(

This is what is currently in the logs:
```
2021-01-24T17:23:55.005981+00:00 app[scheduler.7427]: Fetching the SHA for live BinderHub and repo2docker...
2021-01-24T17:23:55.098378+00:00 app[scheduler.7427]: {'apiVersion': 'v2', 'description': 'A meta-chart for the binderhub deployment on mybinder.org', 'name': 'mybinder', 'version': '0.1.0', 'kubeVersion': '>= 1.15.0-0', 'dependencies': [{'name': 'ingress-nginx', 'version': '2.13.0', 'repository': 'https://kubernetes.github.io/ingress-nginx'}, {'name': 'prometheus', 'version': '11.16.9', 'repository': 'https://prometheus-community.github.io/helm-charts'}, {'name': 'grafana', 'version': '5.0.26', 'repository': 'https://grafana.github.io/helm-charts'}, {'name': 'binderhub', 'version': '0.2.0-n472.h32e06ee', 'repository': 'https://jupyterhub.github.io/helm-chart'}]}
2021-01-24T17:23:55.269708+00:00 app[scheduler.7427]: Fetching latest commit SHA for BinderHub and repo2docker...
2021-01-24T17:23:55.337540+00:00 app[scheduler.7427]: repo2docker 0.11.0-207.g45229ad 2021.01.0
2021-01-24T17:23:57.038972+00:00 app[scheduler.7427]: binderhub 0.2.0-n472.h32e06ee 0.2.0-n499.h81660eb
2021-01-24T17:23:57.367083+00:00 app[scheduler.7427]: Cloning into 'mybinder.org-deploy'...
2021-01-24T17:23:58.246563+00:00 app[scheduler.7427]: fatal: could not read Username for 'https://github.com': No such device or address
2021-01-24T17:23:58.248782+00:00 app[scheduler.7427]: Traceback (most recent call last):
2021-01-24T17:23:58.248801+00:00 app[scheduler.7427]:   File "src/mybinder-upgrades/henchbot.py", line 386, in <module>
2021-01-24T17:23:58.249273+00:00 app[scheduler.7427]:     hb.update_repos(['repo2docker', 'binderhub'])
2021-01-24T17:23:58.249274+00:00 app[scheduler.7427]:   File "src/mybinder-upgrades/henchbot.py", line 62, in update_repos
2021-01-24T17:23:58.249408+00:00 app[scheduler.7427]:     self.upgrade_repo_commit(existing_pr, repo)
2021-01-24T17:23:58.249424+00:00 app[scheduler.7427]:   File "src/mybinder-upgrades/henchbot.py", line 235, in upgrade_repo_commit
2021-01-24T17:23:58.249607+00:00 app[scheduler.7427]:     self.checkout_branch(existing_pr, repo)
2021-01-24T17:23:58.249612+00:00 app[scheduler.7427]:   File "src/mybinder-upgrades/henchbot.py", line 135, in checkout_branch
2021-01-24T17:23:58.249788+00:00 app[scheduler.7427]:     self.delete_old_branch(repo)
2021-01-24T17:23:58.249812+00:00 app[scheduler.7427]:   File "src/mybinder-upgrades/henchbot.py", line 124, in delete_old_branch
2021-01-24T17:23:58.249961+00:00 app[scheduler.7427]:     ['git', 'push', '--delete', 'origin', repo+'_bump'])
2021-01-24T17:23:58.249984+00:00 app[scheduler.7427]:   File "/app/.heroku/python/lib/python3.7/subprocess.py", line 347, in check_call
2021-01-24T17:23:58.250245+00:00 app[scheduler.7427]:     raise CalledProcessError(retcode, cmd)
2021-01-24T17:23:58.250333+00:00 app[scheduler.7427]: subprocess.CalledProcessError: Command '['git', 'push', '--delete', 'origin', 'repo2docker_bump']' returned non-zero exit status 128.
```

I think deleting the `bump_repo2docker` branch in https://github.com/henchbot/mybinder.org-deploy would get us unblocked.

One weird log message I don't understand is "fatal: could not read Username for 'https://github.com': No such device or address"

**Comment by betatim** [comment]
I wonder if we need to do something like https://github.com/henchbot/mybinder.org-upgrades/blob/master/src/mybinder-upgrades/henchbot.py#L223 to pass the token to the `git push`. Or find a way to configure `git` itself to always use the token?

**Comment by betatim** [comment]
I used the token from heroku to manually delete the `repo2docker_bump` branch on the deploy repo.

I think we can fix/avoid this problem by cloning the repo as `git clone https://henchbot:$TOKEN@github.com/henchbot/mybinder.org-deploy`. That way the token is available for later commands. However it means the token is a bit more exposed than otherwise. Setting up `GIT_ASKPASS` is probably the right thing to do, but that is a bit involved.

**Comment by consideRatio** [comment]
Related to #6:

A GitHub workflow triggered by cron/push on jupyterhub/mybinder.org-deploy automatically have rights to push to itself if I remember correctly, using temporary credentials. These can also be passed explicitly when needed using `${{ secrets.GITHUB_TOKEN }}`.

**Comment by henchc** [comment]
It looks like it's working again? Is this right now? https://github.com/jupyterhub/mybinder.org-deploy/pull/1793

Thanks for the updates @consideRatio  and @betatim .

As for authentication, this was never an issue before, did GitHub change API token authorization?

**Comment by betatim** [comment]
> It looks like it's working again? Is this right now? [jupyterhub/mybinder.org-deploy#1793](https://github.com/jupyterhub/mybinder.org-deploy/pull/1793)

Yes it works again because I manually deleted the branch.

I think henchbot would get stuck again if the situation happens again.

I think we never noticed this before because the method that deletes a branch couldn't be called because of #8. So I think we are discovering things that don't work in that code because they weren't used till now.
